### ISSUE TITLE
Tools to check out — split into individual issues

### ISSUE THREAD

**Issue by arran4** [arran4/dotfiles#20]
This catch-all issue has been split into individual issues:

- [ ] #331 — Evaluate Alacritty for dotfiles
- [ ] #332 — Evaluate Starship prompt for dotfiles
- [ ] #333 — Evaluate picom compositor for dotfiles
- [ ] #334 — Evaluate kitty terminal for dotfiles
- [ ] #335 — Evaluate btop for dotfiles

The individual issues are now the canonical places to track evaluation and any resulting configuration work.

**Comment by arran4** [comment]
https://starship.rs/

**Comment by arran4** [comment]
https://github.com/jonaburg/picom

**Comment by arran4** [comment]
https://sw.kovidgoyal.net/kitty/

**Comment by arran4** [comment]
https://github.com/aristocratos/btop
